### ISSUE TITLE
Strange exception with Ruby 2.1

### ISSUE THREAD

**Issue by eka** [defunkt/fakefs#214]
If I don't require fakefs everything runs ok.

```
ruby --version
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin13.0]
```

```
/usr/local/Cellar/ruby/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:748:in `block in _resort!': undefined method `name' for nil:NilClass (NoMethodError)
        from /usr/local/Cellar/ruby/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:747:in `sort!'
        from /usr/local/Cellar/ruby/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:747:in `_resort!'
        from /usr/local/Cellar/ruby/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:699:in `_all'
        from /usr/local/Cellar/ruby/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:882:in `each'
        from /usr/local/Cellar/ruby/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems.rb:428:in `map'
        from /usr/local/Cellar/ruby/2.1.0/lib/ruby/site_ruby/2.1.0/rubygems.r
```

```
gem  list

*** LOCAL GEMS ***

activesupport (4.0.2)
atomic (1.1.14)
bigdecimal (1.2.3)
bundler (1.5.2)
celluloid (0.15.2)
coderay (1.1.0)
erubis (2.7.0)
fakefs (0.5.0)
ffi (1.9.3)
formatador (0.2.4)
guard (2.3.0)
guard-minitest (2.2.0)
hanuman (0.0.1)
i18n (0.6.9)
io-console (0.4.2)
json (1.8.1)
listen (2.4.0)
lumberjack (1.0.4)
method_source (0.8.2)
minitest (5.2.2, 4.7.5)
multi_json (1.8.4)
pry (0.9.12.5)
psych (2.0.2)
rake (10.1.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.3)
rdoc (4.1.0)
rubygems-update (2.2.1)
slop (3.4.7)
terminal-notifier-guard (1.5.3)
test-unit (2.1.0.0)
thor (0.18.1)
thread_safe (0.1.3)
timers (1.1.0)
tmuxinator (0.6.6)
tzinfo (0.3.38)
```

**Comment by sometimesfood** [comment]
@eka Do you still experience this problem? I can't reproduce it:

```
~/src/fakefs (git)-[master] % ruby --version                   
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
~/src/fakefs (git)-[master] % cat minitest-test.rb
require 'minitest/autorun'
require 'fakefs'
~/src/fakefs (git)-[master] % bundle exec ruby minitest-test.rb
Run options: --seed 45938

# Running:



Finished in 0.001310s, 0.0000 runs/s, 0.0000 assertions/s.

0 runs, 0 assertions, 0 failures, 0 errors, 0 skips
~/src/fakefs (git)-[master] % 
```

As pointed out by @eventualbuddha I run into #215 with rspec, but minitest works fine and in either case I am not able to reproduce your exception above.

**Comment by eka** [comment]
This was a blocker so I stop trying and worked for an alternative, can't say.

thanks anyway

**Comment by sometimesfood** [comment]
Sorry to hear that. I vaguely remember having some problems with fakefs and Ruby 2.1.0 myself and holding off on the upgrade. Seems to have been fixed by now, though.
