### ISSUE TITLE
Tests don't pass out of the box?

### ISSUE THREAD

**Issue by zenspider** [defunkt/fakefs#216]
I'm working on a bug that I'd like to submit a patch for, but I can't verify that the current tests even work.

```
% bundle exec rake
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -I"lib:test" -I"/Users/ryan/.gem/repos/blech/gems/rake-10.1.1/lib" "/Users/ryan/.gem/repos/blech/gems/rake-10.1.1/lib/rake/rake_test_loader.rb" "test/fake/file/join_test.rb" "test/fake/file/lstat_test.rb" "test/fake/file/stat_test.rb" "test/fake/file/sysseek_test.rb" "test/fake/file/syswrite_test.rb" "test/fake/file_test.rb" "test/fake/symlink_test.rb" "test/fakefs_test.rb" "test/file/stat_test.rb" "test/safe_test.rb" 
Run options: 

# Running tests:

..................................................F...................................../Users/ryan/Work/git/fakefs/lib/fakefs/fake/dir.rb:28: warning: FakeFS::FakeSymlink#respond_to?(:marshal_dump) is old fashion which takes only one parameter
/Users/ryan/Work/git/fakefs/lib/fakefs/fake/symlink.rb:25: warning: respond_to? is defined here
/Users/ryan/Work/git/fakefs/lib/fakefs/fake/dir.rb:28: warning: FakeFS::FakeSymlink#respond_to?(:_dump) is old fashion which takes only one parameter
/Users/ryan/Work/git/fakefs/lib/fakefs/fake/symlink.rb:25: warning: respond_to? is defined here
...........................................................F................................................................................................................................................E.EE.E.....................

Finished tests in 0.392803s, 812.1119 tests/s, 1708.2354 assertions/s.

  1) Failure:
test_can_read_binary_data_in_binary_mode(FakeFSTest) [/Users/ryan/Work/git/fakefs/test/fakefs_test.rb:2449]:
<"\u0000\u0000\u0000\u0003\u0000\u0003\u0000\xA3\u0000\u0000\u0000y\u0000\u0000\u0000\u0000\u0000"> expected but was
<"\x00\x00\x00\x03\x00\x03\x00\xA3\x00\x00\x00y\x00\x00\x00\x00\x00">.

  2) Failure:
test_every_method_in_file_is_in_fake_fs_file(FakeFSTest) [/Users/ryan/Work/git/fakefs/test/fakefs_test.rb:1098]:
raw method is not available in File :(

  3) Error:
test_should_report_on_symlink_itself_with_size_instance_method(FileStat):
Errno::ENOENT: No such file or directory - No such file or directory - my_symlink
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:289:in `initialize'
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:239:in `new'
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:239:in `lstat'
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:402:in `lstat'
    /Users/ryan/Work/git/fakefs/test/fake/file/lstat_test.rb:47:in `test_should_report_on_symlink_itself_with_size_instance_method'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1301:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/testcase.rb:17:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:919:in `block in _run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `map'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `_run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:657:in `block in _run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `_run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:867:in `_run_anything'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1060:in `run_tests'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1047:in `block in _run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `_run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1035:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:21:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:774:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:366:in `block (2 levels) in autorun'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:27:in `run_once'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:365:in `block in autorun'

  4) Error:
test_lstat_should_report_on_symlink_itself(FileStat):
Errno::ENOENT: No such file or directory - No such file or directory - my_symlink
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:289:in `initialize'
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:239:in `new'
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:239:in `lstat'
    /Users/ryan/Work/git/fakefs/test/fake/file/lstat_test.rb:37:in `test_lstat_should_report_on_symlink_itself'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1301:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/testcase.rb:17:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:919:in `block in _run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `map'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `_run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:657:in `block in _run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `_run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:867:in `_run_anything'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1060:in `run_tests'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1047:in `block in _run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `_run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1035:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:21:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:774:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:366:in `block (2 levels) in autorun'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:27:in `run_once'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:365:in `block in autorun'

  5) Error:
test_stat_should_report_on_symlink_pointer(FileStat):
Errno::ENOENT: No such file or directory - No such file or directory - my_symlink
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:289:in `initialize'
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:235:in `new'
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:235:in `stat'
    /Users/ryan/Work/git/fakefs/test/fake/file/stat_test.rb:37:in `test_stat_should_report_on_symlink_pointer'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1301:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/testcase.rb:17:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:919:in `block in _run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `map'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `_run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:657:in `block in _run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `_run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:867:in `_run_anything'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1060:in `run_tests'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1047:in `block in _run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `_run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1035:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:21:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:774:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:366:in `block (2 levels) in autorun'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:27:in `run_once'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:365:in `block in autorun'

  6) Error:
test_symlink_size_is_size_of_path_pointed_to(FileStat):
Errno::ENOENT: No such file or directory - No such file or directory - one_char_symlink
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:289:in `initialize'
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:239:in `new'
    /Users/ryan/Work/git/fakefs/lib/fakefs/file.rb:239:in `lstat'
    /Users/ryan/Work/git/fakefs/test/fake/file/lstat_test.rb:53:in `test_symlink_size_is_size_of_path_pointed_to'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1301:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit/testcase.rb:17:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:919:in `block in _run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `map'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:912:in `_run_suite'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:657:in `block in _run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:655:in `_run_suites'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:867:in `_run_anything'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1060:in `run_tests'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1047:in `block in _run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `each'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1046:in `_run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/minitest/unit.rb:1035:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:21:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:774:in `run'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:366:in `block (2 levels) in autorun'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:27:in `run_once'
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/test/unit.rb:365:in `block in autorun'

319 tests, 671 assertions, 2 failures, 4 errors, 0 skips

ruby -v: ruby 2.0.0p247 (2013-06-27 revision 41674) [universal.x86_64-darwin13]
rake aborted!
Command failed with status (6): [ruby -I"lib:test" -I"/Users/ryan/.gem/repos/blech/gems/rake-10.1.1/lib" "/Users/ryan/.gem/repos/blech/gems/rake-10.1.1/lib/rake/rake_test_loader.rb" "test/fake/file/join_test.rb" "test/fake/file/lstat_test.rb" "test/fake/file/stat_test.rb" "test/fake/file/sysseek_test.rb" "test/fake/file/syswrite_test.rb" "test/fake/file_test.rb" "test/fake/symlink_test.rb" "test/fakefs_test.rb" "test/file/stat_test.rb" "test/safe_test.rb" ]

Tasks: TOP => default => test
(See full trace by running task with --trace)
```

**Comment by smtlaissezfaire** [comment]
It's been 6 months.  Closing this one out.
