### ISSUE TITLE
Kernel hijacking and open-uri failures

### ISSUE THREAD

**Issue by bquorning** [defunkt/fakefs#312]
FakeFS and `open-uri`’s `Kernel.open` don’t work well together.

Introduced in #226; related to #290.

cc @dekz, @eventualbuddha 

Requiring `open-uri` before or after `fakefs` changes the error message. Also note that I don’t even call `FakeFS.activate!`. If I add it (before `FakeFS.deactivate!`), the error message is the same.

```rb
# test1.rb
require 'open-uri'
require 'fakefs/safe'

FakeFS.deactivate!

Kernel.open('/tmp/existing-file')
```
```
Code/fakefs ‹2.2.3p173› ‹master*› » ruby test1.rb
/Users/bquorning/.rubies/ruby-2.2.3/lib/ruby/2.2.0/open-uri.rb:28:in `open': wrong number of arguments (0 for 1+) (ArgumentError)
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `call'
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `block (2 levels) in unhijack!'
  from /Users/bquorning/.rubies/ruby-2.2.3/lib/ruby/2.2.0/open-uri.rb:30:in `open'
  from test1.rb:7:in `<main>'
```

```rb
# test2.rb
require 'fakefs/safe'
require 'open-uri'

FakeFS.deactivate!

Kernel.open('/tmp/existing-file')
```
```
Code/fakefs ‹2.2.3p173› ‹master*› » ruby test2.rb
/Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `initialize': wrong number of arguments (0 for 1..3) (ArgumentError)
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `open'
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `call'
  from /Users/bquorning/.gem/ruby/2.2.3/gems/fakefs-0.6.7/lib/fakefs/kernel.rb:21:in `block (2 levels) in unhijack!'
  from /Users/bquorning/.rubies/ruby-2.2.3/lib/ruby/2.2.0/open-uri.rb:30:in `open'
  from test2.rb:7:in `<main>'
```

**Comment by dekz** [comment]
```ruby
def test(str)
  puts("- #{str}")
  a = "\tString respond to :open?"
  puts(a, a.respond_to?(:open))
end

test('Before require')
require 'pry'
require 'fakefs/safe'
require 'open-uri'

test('After require')

FakeFS.deactivate!

test('After deactivate')

Kernel.open('/tmp/existing-file')

```

It seems to be an issue with the `hijack` actually defining `:open` on every Object, UH OH!

**Comment by bquorning** [comment]
> UH OH!

Indeed :-)

**Comment by dekz** [comment]
@bquorning can you give that PR a test and tell me if it works?

**Comment by bquorning** [comment]
@dekz, this does indeed solve those two simple test cases. However, my “real-world” test case that I had reduced it from still fails. I will try find new, minimal reproducible test case for you :-)

**Comment by bquorning** [comment]
Yeah, `Kernel.open` doesn’t properly work with URLs after enabling/disabling FakeFS:

```rb
# test3.rb
require 'open-uri'
require 'fakefs/safe'

Kernel.open('http://google.com') && puts("Works before activating")

FakeFS.activate!

Kernel.open('http://google.com') && puts("Works after activating")
```
```
Code/fakefs ‹2.2.3p173› ‹(4c3215e...)*› » ruby -Ilib test3.rb
Works before activating
/Users/bquorning/Code/fakefs/lib/fakefs/file.rb:599:in `check_file_existence!': No such file or directory - http://google.com (Errno::ENOENT)
  from /Users/bquorning/Code/fakefs/lib/fakefs/file.rb:383:in `initialize'
  from /Users/bquorning/Code/fakefs/lib/fakefs/kernel.rb:56:in `open'
  from /Users/bquorning/Code/fakefs/lib/fakefs/kernel.rb:56:in `block in <module:Kernel>'
  from test3.rb:9:in `<main>'
```

```rb
# test4.rb
require 'open-uri'
require 'fakefs/safe'

Kernel.open('http://google.com') && puts("Works before activating")

FakeFS.activate!
FakeFS.deactivate!

Kernel.open('http://google.com') && puts("Works after deactivating")
```
```
Code/fakefs ‹2.2.3p173› ‹(4c3215e...)*› » ruby -Ilib test4.rb
Works before activating
/Users/bquorning/Code/fakefs/lib/fakefs/file.rb:599:in `check_file_existence!': No such file or directory - http://google.com (Errno::ENOENT)
  from /Users/bquorning/Code/fakefs/lib/fakefs/file.rb:383:in `initialize'
  from /Users/bquorning/Code/fakefs/lib/fakefs/kernel.rb:56:in `open'
  from /Users/bquorning/Code/fakefs/lib/fakefs/kernel.rb:56:in `block in <module:Kernel>'
  from test4.rb:10:in `<main>'
```

**Comment by dekz** [comment]
I added a URI check in 14ba4edd84c4706575bbeffa531ffe9ae448ff83 so if you want to get that a test for me, here is my output from your tests:

```
~/t/f/tests ❯❯❯ be ruby test4.rb
Works before activating
Works after deactivating
```

```
[1] ~/t/f/tests ❯❯❯ be ruby test3.rb
Works before activating
/Users/jacob/tmp/fakefs/fakefs/lib/fakefs/file.rb:627:in `create_missing_file': No such file or directory - /tmp/open-uri20150925--1y6xsfa (Errno::ENOENT)
	from /Users/jacob/tmp/fakefs/fakefs/lib/fakefs/file.rb:383:in `initialize'
	from /Users/jacob/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tempfile.rb:136:in `open'
	from /Users/jacob/.rbenv/versions/2.2.2/lib/ruby/2.2.0/tempfile.rb:136:in `block in initialize'
```


Seems like open-uri wants to write to a tmp file, so before using openuri with fakefs you might have to make sure that directory is created!

**Comment by bquorning** [comment]
Yeah, it still doesn’t work for me. Maybe I just should not use fakefs and open-uri together :-)

**Comment by dekz** [comment]
What's the error you're seeing now mate?

**Comment by bquorning** [comment]
My “real” test case includes Carrierwave and Fog, so my test output is just something about calling a method on a `nil` object where I expected to have a Carrierwave file object. I believe it’s caused by the same circumstances as in test3.rb.

I’ll try to condense my test case a bit, and report back here.

**Comment by rmm5t** [comment]
@dekz @bquorning
I just ran into this same issue myself while trying to use `WEBrick::HTTPAuth::Htdigest` in an environment that also loads FakeFS. `Htdigest` relies on `Kernel.open` and I saw the same behavior that @bquorning originally saw.

The PR in #313 actually solves the issue. Of course, in my scenario, I'm not trying to open a URL resource.

**Comment by bquorning** [comment]
I’ll confirm that #319 solves my problem.
