### ISSUE TITLE
Byebug doesn't load after requiring fakefs

### ISSUE THREAD

**Issue by eterry1388** [defunkt/fakefs#322]
Using `irb` I required fakefs and then required byebug.  Got a bunch of "Ignoring" errors and finally a `LoadError` for byebug.

```
2.2.1 :001 > require 'fakefs'
 => true 
2.2.1 :002 > require 'byebug'
Ignoring atomic-1.1.14 because its extensions are not built.  Try: gem pristine atomic --version 1.1.14
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring byebug-6.0.2 because its extensions are not built.  Try: gem pristine byebug --version 6.0.2
Ignoring byebug-5.0.0 because its extensions are not built.  Try: gem pristine byebug --version 5.0.0
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring eventmachine-1.0.8 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.8
Ignoring eventmachine-1.0.7 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.7
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring gherkin-2.12.2 because its extensions are not built.  Try: gem pristine gherkin --version 2.12.2
Ignoring god-0.13.6 because its extensions are not built.  Try: gem pristine god --version 0.13.6
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring json-1.8.2 because its extensions are not built.  Try: gem pristine json --version 1.8.2
Ignoring kgio-2.10.0 because its extensions are not built.  Try: gem pristine kgio --version 2.10.0
Ignoring libxml-ruby-2.8.0 because its extensions are not built.  Try: gem pristine libxml-ruby --version 2.8.0
Ignoring mysql2-0.3.18 because its extensions are not built.  Try: gem pristine mysql2 --version 0.3.18
Ignoring nokogiri-1.6.6.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.6.2
Ignoring nokogiri-1.6.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.1
Ignoring posix-spawn-0.3.11 because its extensions are not built.  Try: gem pristine posix-spawn --version 0.3.11
Ignoring raindrops-0.15.0 because its extensions are not built.  Try: gem pristine raindrops --version 0.15.0
Ignoring redcarpet-3.3.2 because its extensions are not built.  Try: gem pristine redcarpet --version 3.3.2
Ignoring rugged-0.23.3 because its extensions are not built.  Try: gem pristine rugged --version 0.23.3
Ignoring skylight-0.6.1 because its extensions are not built.  Try: gem pristine skylight --version 0.6.1
Ignoring sqlite3-1.3.11 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.11
Ignoring sqlite3-1.3.10 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.10
Ignoring therubyracer-0.12.2 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.2
Ignoring thin-1.6.4 because its extensions are not built.  Try: gem pristine thin --version 1.6.4
Ignoring thin-1.6.3 because its extensions are not built.  Try: gem pristine thin --version 1.6.3
Ignoring unf_ext-0.0.7.1 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.1
Ignoring unf_ext-0.0.6 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.6
Ignoring unicorn-5.0.0 because its extensions are not built.  Try: gem pristine unicorn --version 5.0.0
Ignoring atomic-1.1.14 because its extensions are not built.  Try: gem pristine atomic --version 1.1.14
Ignoring bcrypt-3.1.10 because its extensions are not built.  Try: gem pristine bcrypt --version 3.1.10
Ignoring binding_of_caller-0.7.2 because its extensions are not built.  Try: gem pristine binding_of_caller --version 0.7.2
Ignoring byebug-8.2.1 because its extensions are not built.  Try: gem pristine byebug --version 8.2.1
Ignoring byebug-6.0.2 because its extensions are not built.  Try: gem pristine byebug --version 6.0.2
Ignoring byebug-5.0.0 because its extensions are not built.  Try: gem pristine byebug --version 5.0.0
Ignoring debug_inspector-0.0.2 because its extensions are not built.  Try: gem pristine debug_inspector --version 0.0.2
Ignoring eventmachine-1.0.8 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.8
Ignoring eventmachine-1.0.7 because its extensions are not built.  Try: gem pristine eventmachine --version 1.0.7
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.10 because its extensions are not built.  Try: gem pristine ffi --version 1.9.10
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring gherkin-2.12.2 because its extensions are not built.  Try: gem pristine gherkin --version 2.12.2
Ignoring god-0.13.6 because its extensions are not built.  Try: gem pristine god --version 0.13.6
Ignoring http_parser.rb-0.6.0 because its extensions are not built.  Try: gem pristine http_parser.rb --version 0.6.0
Ignoring json-1.8.3 because its extensions are not built.  Try: gem pristine json --version 1.8.3
Ignoring json-1.8.2 because its extensions are not built.  Try: gem pristine json --version 1.8.2
Ignoring kgio-2.10.0 because its extensions are not built.  Try: gem pristine kgio --version 2.10.0
Ignoring libxml-ruby-2.8.0 because its extensions are not built.  Try: gem pristine libxml-ruby --version 2.8.0
Ignoring mysql2-0.3.18 because its extensions are not built.  Try: gem pristine mysql2 --version 0.3.18
Ignoring nokogiri-1.6.6.2 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.6.2
Ignoring nokogiri-1.6.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.1
Ignoring posix-spawn-0.3.11 because its extensions are not built.  Try: gem pristine posix-spawn --version 0.3.11
Ignoring raindrops-0.15.0 because its extensions are not built.  Try: gem pristine raindrops --version 0.15.0
Ignoring redcarpet-3.3.2 because its extensions are not built.  Try: gem pristine redcarpet --version 3.3.2
Ignoring rugged-0.23.3 because its extensions are not built.  Try: gem pristine rugged --version 0.23.3
Ignoring skylight-0.6.1 because its extensions are not built.  Try: gem pristine skylight --version 0.6.1
Ignoring sqlite3-1.3.11 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.11
Ignoring sqlite3-1.3.10 because its extensions are not built.  Try: gem pristine sqlite3 --version 1.3.10
Ignoring therubyracer-0.12.2 because its extensions are not built.  Try: gem pristine therubyracer --version 0.12.2
Ignoring thin-1.6.4 because its extensions are not built.  Try: gem pristine thin --version 1.6.4
Ignoring thin-1.6.3 because its extensions are not built.  Try: gem pristine thin --version 1.6.3
Ignoring unf_ext-0.0.7.1 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.7.1
Ignoring unf_ext-0.0.6 because its extensions are not built.  Try: gem pristine unf_ext --version 0.0.6
Ignoring unicorn-5.0.0 because its extensions are not built.  Try: gem pristine unicorn --version 5.0.0
LoadError: cannot load such file -- byebug
	from /home/eterry/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/eterry/.rvm/rubies/ruby-2.2.1/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from (irb):2
	from /home/eterry/.rvm/rubies/ruby-2.2.1/bin/irb:11:in `<main>'
```

**Comment by bquorning** [comment]
That’s because `require 'fakefs'` activates FakeFS right away, so you’re asking `require` to locate byebug on the fake file system.

See https://github.com/defunkt/fakefs#dont-fake-the-fs-immediately

**Comment by eterry1388** [comment]
Hmm. I tried this and got this error:
`undefined method 'platform' for nil:NilClass`

```ruby
require 'byebug'
require 'fakefs/safe'

FakeFS.activate!

byebug
FileUtils.mkdir_p( '/tmp/test' )

FakeFS.deactivate!
```

And I tried this (which got into byebug), but when I tried to step over the program, I got this error:
`*** No sourcefile available for test.rb`

```ruby
require 'byebug'
require 'fakefs/safe'

byebug

FakeFS.activate!

# your code
FileUtils.mkdir_p( '/tmp/test' )

FakeFS.deactivate!
```

**Comment by bquorning** [comment]
Looks like `byebug` depends on the file system that `fakefs` removes. Logging is also not an option, so I guess you're left with `puts` for debugging.

**Comment by eterry1388** [comment]
Ok thanks!

**Comment by ConorSheehan1** [comment]
Is there any way to allow byebug to use the file system while stubbing it for all other calls?
